### ISSUE TITLE
Linear Ramp at the beginning of a new tab

### ISSUE THREAD

**Issue by tripiti** [coldphysics/experiment-control#3]
**Describe the bug**
If a linear ramp starts at the beginning of a new tab, it will cause strange behaviour of the output. A short constant time step before the linear ramp resolves this issue.

**To Reproduce**
1. load a experimetal sequence with a linear ramp at the beginning of a new tab
2. run it and look at your atoms
3. create a short timestep with a constant value before the linear ramp starts (in our case 0.02ms)
4. See a drastic change in your atom number

**Expected behavior**
A linear ramp at the analog output without any need of a constant time step before.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Software Control Version 1.3.0.25 (svn 757-08.11.2019)
 - Hardware Type  AdWin

**Comment by ghareeb-falazi** [comment]
Could you please provide an example model file that is causing this issue?

**Comment by ghareeb-falazi** [comment]
I think the root cause of the problem is how many samples the program produces for each time step. It is defined by the relation `total_step_duration / minimum_step_duration` where `minimum_step_duration` is determined by the sample rate of the specific experiment under question.
For example, for a sample rate of 50 kHz, the minimum step duration is 0.02 milliseconds. So, if we have a step (of any type) of duration 0.1 ms, then we will have 5 samples given as output at times (0, 0.02, 0.04, 0.06, 0.08). 

See the card window:
![image](https://user-images.githubusercontent.com/28387669/79871850-47964000-83e5-11ea-9d42-06910d3bdeb4.png)

And see the output visualizer:
![image](https://user-images.githubusercontent.com/28387669/79871481-b32bdd80-83e4-11ea-9723-2ed2aeb47443.png)
Notice how no sample is output at time 0.1! This is done this way since the next step will start exactly at time 0.1.

For ramp steps, **there was a discussion made before**: Consider a ramp step that should go from value `v1` to value `v2` during a duration `d` starting form time `t0` (the slope `s = (v2-v1)/d` and the voltage value differs by the amount `slope_step = s * minimum_step_duration` between any two consecutive samples of the ramp).
Since the last sample output is not exactly at `t0 + d`, but rather `t0 + d - minimum_step_duration`, we have to choose one of the following options:
  1. the first sample has the coordinates `(t0, v1)` and the last one has the coordinates `(t0 + d - minimum_step_duration, v2 - slope_step)`
  2. the first sample has the coordinates `(t0, v1 + slope_step)` and the last one has the coordinates `(t0 + d - minimumb_step_duration, v2)`

The discussion resulted in picking option 2, since it was considered mandatory that the end of the ramp must give exactly the output value given by the user, i.e., v2 (consider, e.g., a ramp at the very end of the model). See the following example, which extends the previous one (here, two tabs are used just to have the output visualizer color the background for the two steps differently). The first sample of the ramp is at `(0.1 ms, 6 v)` and the last one is at `(0.18 ms, 10 v)`.

![image](https://user-images.githubusercontent.com/28387669/79879390-e4111000-83ee-11ea-9f0e-8da65f7daad8.png)

![image](https://user-images.githubusercontent.com/28387669/79871738-161d7480-83e5-11ea-9c78-41d90b78bf3a.png)

**I assume the problem you are facing** is a result of choosing option 2: the first sample output by the ramp step is not exactly the first expected voltage value, but rather a little more (or less depending on the slope).

**I think a better option 3 exists:** change the slope value from `s_old = (v2-v1)/d` to `s_new = (v2-v1)/(d-minimum_step_duration)`. This way the first sample can be at `(t0, v1)`, and the last sample at 
`(t0 + d - minimumb_step_duration, v2)`.

**However**, such a change will probably affect all the running experiments having ramp steps. Therefore, a decision to introduce any change with step outputs must be done after discussing with the whole group.

**Comment by ghareeb-falazi** [comment]
After discussion with the group, it is decided to keep the behavior as it is now. Since there is no perfect way to solve it, the priority is to keep the last value of the ramp at the desired value, and not change the ramp value as well. @tripiti  if you think we missed something in this discussion, please reopen the issue and provide more details.
